// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA08DA74zSO8Vwv98PjeCKUOKmBAtjtibk',
    appId: '1:868338942906:web:63dc11e3a04546a8165383',
    messagingSenderId: '868338942906',
    projectId: 'chat-and-notes',
    authDomain: 'chat-and-notes.firebaseapp.com',
    storageBucket: 'chat-and-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABhALhl6vdYB_55AaUWWlCMvqB5f3PuN8',
    appId: '1:868338942906:android:7f894771628bc568165383',
    messagingSenderId: '868338942906',
    projectId: 'chat-and-notes',
    storageBucket: 'chat-and-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2jvaRmoFAAXfekZ-rwqMSJPNQeVQ1JU',
    appId: '1:868338942906:ios:eb7a82ce6078c098165383',
    messagingSenderId: '868338942906',
    projectId: 'chat-and-notes',
    storageBucket: 'chat-and-notes.appspot.com',
    iosBundleId: 'com.example.rsmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD2jvaRmoFAAXfekZ-rwqMSJPNQeVQ1JU',
    appId: '1:868338942906:ios:5cd9cbb0f6e77130165383',
    messagingSenderId: '868338942906',
    projectId: 'chat-and-notes',
    storageBucket: 'chat-and-notes.appspot.com',
    iosBundleId: 'com.example.rsmApp.RunnerTests',
  );
}
